name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Task
        uses: go-task/setup-task@v2

      - name: Install dependencies
        run: bun ci

      - name: Validate
        run: task validate

      - name: Test
        run: task test

      - name: Build
        run: task build
